# fly.toml file generated for ellada-api on 2023-02-07T02:10:18-05:00

app = "ellada-api"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "3000"
  JWT_TOKEN_AUDIENCE = "ellada-api.fly.dev"
  JWT_TOKEN_ISSUER = "ellada-api.fly.dev"
  JWT_ACCESS_TOKEN_TTL = 3600
  JWT_REFRESH_TOKEN_TTL = 86400

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
